baseURL = "http://pipedev.org/"
languageCode = "en-us"
title = "Pipeline Developer Forum"
summaryLength = 25

[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "github"
tabWidth = 4
[markup.goldmark.renderer]
# ensure our embedded url gets properly propagated
unsafe = true
